### ISSUE TITLE
Update README with note re: application name

### ISSUE THREAD

**Issue by agileadam** [elromanos/webfaction-tomcat-7-installer#1]
Hello,
Thanks for your work on this!

I thought your script was broken when I was getting an error: "There was an error creating the app with the custom script." It turns out that I had to name my application something other than "tomcat".

I'm not sure if this problem was unique to my environment, but using a different app name worked.

Thanks again!
Adam

**Comment by agileadam** [comment]
Hello again,

I logged into the server and noticed, even though the install script was failing when I tried to create an application called "tomcat", I did have a ~/webapps/tomcat directory (that was empty). I wonder if it couldn't install because for some reason that directory may have already existed?

I do not have permission to delete the ~/webapps/tomcat directory so I cannot try it again. As soon as WF answers my support ticket and deletes the directory I can try your script again using "tomcat" as the application name.

Regardless, your script worked beautifully with a different app name.

**Comment by elromanos** [comment]
I've used "tomcat" a few times while testing this and never had an issue.

WebFaction's installer will fail if a directory with the same name as the app exists in the ~/webapps directory, so it should work as soon as support removes that. If not, I'll give it another look.

**Comment by agileadam** [comment]
Yeah, sorry to post a non-issue if it was just my particular environment.
If I could test again right now I would.
Thanks for responding so quickly,
Adam

**Comment by agileadam** [comment]
Sorry for the scare! I had WF delete the directory, and I just tried "tomcat" as the application name. It worked like a charm.
Thanks so much!

I'll close this.
